name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build

  publish-npm:
    env:
      NPM_CONFIG_TOKEN: ${{secrets.npm_token}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set tokens
        run: echo "//registry.npmjs.org/:_authToken=${{env.NPM_CONFIG_TOKEN}}" >> ~/.npmrc
      - run: bun install
      - run: bun publish --access public

  publish-gpr:
    env:
      NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set tokens
        run: echo "//npm.pkg.github.com/:_authToken=${{env.NPM_CONFIG_TOKEN}}" >> ~/.npmrc
      - run: bun install
      - run: bun publish --access public
